# Default values for backend-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
    name: backend-service
    namespace: qa
    labels:
      app: backend-service
service:
  type: NodePort
spec:   
   name: backend-svc
   selector:
      app: backend-service
   replicas: 1
   template:
      annotations:
        timestamp: 20200526_065337
   containers:
        name: backend-service
   
   resources:
      limits:
         memory: 512Mi
         cpu: 500m
      requests:
         memory: 512Mi
         cpu: 500m
   image:
      name: gcr.io/varshaprocurant-poc/backend-service
      tag: 1.0.1-snapshot-1d3b111
ports:
  containerPort: 9001
  port: 9001
  name: backend-svc
tolerations:
  key: podtype
  operator: Equal
  value: service
  effect: NoSchedule
