# Default values for backend-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
    name: backend-service
    namespace: demo
    labels:
      app: backend-service
spec:   
   name: backend-svc
   selector:
      app: backend-service
   replicas: 1
   template:
      annotations:
        timestamp: 20200526_065337
   containers:
        name: backend-service
   
   resources:
      limits:
         memory: 2000Mi
         cpu: 0
      requests:
         memory: 2000Mi
         cpu: 0
   image:
      name: gcr.io/varshaprocurant-poc/backend-service
      tag: 1.0.1-snapshot-fa45d45
ports:
  containerPort: 8084
  port: 8084
  name: backend-svc
tolerations:
  key: podtype
  operator: Equal
  value: service
  effect: NoSchedule
