apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }} 
  namespace: {{ .Values.metadata.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.spec.selector.app }} # has to match .spec.template.metadata.labels
  replicas: {{ .Values.spec.replicas }}  # by default is 1
  template:
    metadata:
      labels:
        app: {{ .Values.spec.selector.app }} # has to match .spec.selector.matchLabels
      annotations:
        timestamp: "{{ .Values.spec.template.annotations.timestamp }}"  
    spec:
      containers:
      - name: {{ .Values.spec.containers.name }}
        image: "{{ .Values.spec.image.name }}:{{ .Values.spec.image.tag }}"
        imagePullPolicy: Always
        resources:
          limits:
            memory: {{ .Values.spec.resources.limits.memory }}
            cpu: {{ .Values.spec.resources.limits.cpu }}
          requests:
            memory: {{ .Values.spec.resources.requests.memory }}
            cpu: {{ .Values.spec.resources.requests.cpu }}
      
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
          name: {{ .Values.ports.name }}

      tolerations:
      - key: {{ .Values.tolerations.key }}
        operator: {{ .Values.tolerations.operator }}
        value: {{ .Values.tolerations.value }}
        effect: {{ .Values.tolerations.effect }}