# Default values for frontend-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
    name: frontend-service
    namespace: qa
    labels:
      app: frontend-service
spec:   
   name: frontend-svc
   selector:
      app: frontend-service
   replicas: 1
   template:
      annotations:
        timestamp: 20200526_065337
   containers:
        name: frontend-service
   
   resources:
      limits:
         memory: 2000Mi
         cpu: 0
      requests:
         memory: 2000Mi
         cpu: 0
   image:
      name: gcr.io/varshaprocurant-poc/frontend-service
      tag: 1.0.0-snapshot-4dc3f3d
ports:
  containerPort: 8084
  port: 8084
  name: frontend-svc
tolerations:
  key: podtype
  operator: Equal
  value: service
  effect: NoSchedule
